//
// Created by Valentin Ackva on 02/02/2024.
//

#ifndef NN_INFERENCE_TEMPLATE_INFERENCEHANDLER_H
#define NN_INFERENCE_TEMPLATE_INFERENCEHANDLER_H

#endif //NN_INFERENCE_TEMPLATE_INFERENCEHANDLER_H
